version: '3'
services:
    pg-db:
        image: postgres:15
        container_name: local_pg_15
        restart: unless-stopped
        command: postgres -c 'max_connections=400'        
        logging:
            options:
                max-size: 10m
                max-file: "3"
        environment:            
            POSTGRES_DB: votingsystem
            POSTGRES_USER: voting_system
            POSTGRES_PASSWORD: "voting_system"
            PGDATA: /var/lib/postgresql/data
        ports:
            - "5432:5432"
        volumes:             
            - ./data:/var/lib/postgresql/data
